title: Joshua Azemoh
brand: Azemoh
email: joshazemoh@gmail.com
tagline: Programmer 路 Developer 路 Dreamer
motor: Think 路 Learn 路 Create
markdown: redcarpet
baseurl: ""

gems: [
  jekyll-paginate
]

exclude: [
  .git,
  .gitignore,
  CNAME,
  assets/icomoon,
  .sass-cache,
  package.json,
  gulpfile.js,
  node_modules,
  README.md,
  style.html,
  '**/*.map',
  '**/*.scss',
  '**/*.ai',
  '**/*.psd',
  '**/*.log'
]

env: "production"

paginate: 5
paginate_path: "/writing/page:num/"

# SEO
author: Joshua Azemoh
description: "Joshua Azemoh's personal website"


# Site Variables

## Menu
home_menu:
- {name: "Home", url: "#home" }
- {name: "About Me", url: "#about" }
- {name: "Writing", url: "/writing"}
- {name: "Get In Touch", url: "#contact" }

## Social links
socialLinks:
- {name: "github", title: "Github", url: "https://github.com/azemoh"}
- {name: "linkedin", title: "Linkedin", url: "https://linkedin.com/in/azemoh"}
- {name: "twitter", title: "Twitter", url: "http://twitter.com/josh_azemoh"}
- {name: "google-plus", title: "Google+", url: "https://plus.google.com/+JoshuaAzemoh"}
- {name: "email", title: "joshazemoh@gmail.com", url: "mailto://joshazemoh@gmail.com"}
